# Generated by Django 3.2.8 on 2021-10-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('IdEspecie', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEspecie', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaDeOrquideas',
            fields=[
                ('IdFamiliaDeOrquideas', models.AutoField(primary_key=True, serialize=False)),
                ('NombreFamiliaDeOrquideas', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('IdGenero', models.AutoField(primary_key=True, serialize=False)),
                ('NombreGenero', models.CharField(max_length=250)),
            ],
        ),
    ]
